//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ClientProtocol.proto
namespace proto.clientproto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtocolNetRequest")]
  public partial class ProtocolNetRequest : global::ProtoBuf.IExtensible
  {
    public ProtocolNetRequest() {}
    
    private int _cmd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private proto.clientproto.ConnectToServer _connectToServer = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"connectToServer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.clientproto.ConnectToServer connectToServer
    {
      get { return _connectToServer; }
      set { _connectToServer = value; }
    }
    private proto.clientproto.CreateRoom _createRoom = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"createRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.clientproto.CreateRoom createRoom
    {
      get { return _createRoom; }
      set { _createRoom = value; }
    }
    private proto.clientproto.GetRoomList _getRoomList = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"getRoomList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.clientproto.GetRoomList getRoomList
    {
      get { return _getRoomList; }
      set { _getRoomList = value; }
    }
    private proto.clientproto.JoinRoom _joinRoom = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"joinRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.clientproto.JoinRoom joinRoom
    {
      get { return _joinRoom; }
      set { _joinRoom = value; }
    }
    private proto.clientproto.ExitRoom _exitRoom = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"exitRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.clientproto.ExitRoom exitRoom
    {
      get { return _exitRoom; }
      set { _exitRoom = value; }
    }
    private proto.clientproto.RoomOwnerExit _roomOwnerExit = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"roomOwnerExit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.clientproto.RoomOwnerExit roomOwnerExit
    {
      get { return _roomOwnerExit; }
      set { _roomOwnerExit = value; }
    }
    private proto.clientproto.RoomOwnerReadyStartGame _roomOwnerReadyStartGame = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"roomOwnerReadyStartGame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.clientproto.RoomOwnerReadyStartGame roomOwnerReadyStartGame
    {
      get { return _roomOwnerReadyStartGame; }
      set { _roomOwnerReadyStartGame = value; }
    }
    private proto.clientproto.RoomOwnerStartGame _roomOwnerStartGame = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"roomOwnerStartGame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.clientproto.RoomOwnerStartGame roomOwnerStartGame
    {
      get { return _roomOwnerStartGame; }
      set { _roomOwnerStartGame = value; }
    }
    private proto.clientproto.GameResult _gameResult = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"gameResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.clientproto.GameResult gameResult
    {
      get { return _gameResult; }
      set { _gameResult = value; }
    }
    private proto.clientproto.PlayerExitGame _playerExitGame = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"playerExitGame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.clientproto.PlayerExitGame playerExitGame
    {
      get { return _playerExitGame; }
      set { _playerExitGame = value; }
    }
    private proto.clientproto.PlayerReLoadScene _playerReloadScene = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"playerReloadScene", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.clientproto.PlayerReLoadScene playerReloadScene
    {
      get { return _playerReloadScene; }
      set { _playerReloadScene = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConnectToServer")]
  public partial class ConnectToServer : global::ProtoBuf.IExtensible
  {
    public ConnectToServer() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoom")]
  public partial class CreateRoom : global::ProtoBuf.IExtensible
  {
    public CreateRoom() {}
    
    private int _fd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fd
    {
      get { return _fd; }
      set { _fd = value; }
    }
    private string _roomOwner = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomOwner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomOwner
    {
      get { return _roomOwner; }
      set { _roomOwner = value; }
    }
    private int _maxMan = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"maxMan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxMan
    {
      get { return _maxMan; }
      set { _maxMan = value; }
    }
    private string _roomName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetRoomList")]
  public partial class GetRoomList : global::ProtoBuf.IExtensible
  {
    public GetRoomList() {}
    
    private int _fd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fd
    {
      get { return _fd; }
      set { _fd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinRoom")]
  public partial class JoinRoom : global::ProtoBuf.IExtensible
  {
    public JoinRoom() {}
    
    private int _fd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fd
    {
      get { return _fd; }
      set { _fd = value; }
    }
    private int _roomOwnerFd = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomOwnerFd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomOwnerFd
    {
      get { return _roomOwnerFd; }
      set { _roomOwnerFd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExitRoom")]
  public partial class ExitRoom : global::ProtoBuf.IExtensible
  {
    public ExitRoom() {}
    
    private int _fd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fd
    {
      get { return _fd; }
      set { _fd = value; }
    }
    private int _roomOwnerFd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomOwnerFd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomOwnerFd
    {
      get { return _roomOwnerFd; }
      set { _roomOwnerFd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomOwnerExit")]
  public partial class RoomOwnerExit : global::ProtoBuf.IExtensible
  {
    public RoomOwnerExit() {}
    
    private int _fd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fd
    {
      get { return _fd; }
      set { _fd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomOwnerReadyStartGame")]
  public partial class RoomOwnerReadyStartGame : global::ProtoBuf.IExtensible
  {
    public RoomOwnerReadyStartGame() {}
    
    private int _fd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fd
    {
      get { return _fd; }
      set { _fd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomOwnerStartGame")]
  public partial class RoomOwnerStartGame : global::ProtoBuf.IExtensible
  {
    public RoomOwnerStartGame() {}
    
    private int _fd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fd
    {
      get { return _fd; }
      set { _fd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameResult")]
  public partial class GameResult : global::ProtoBuf.IExtensible
  {
    public GameResult() {}
    
    private int _fd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fd
    {
      get { return _fd; }
      set { _fd = value; }
    }
    private bool _result = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerExitGame")]
  public partial class PlayerExitGame : global::ProtoBuf.IExtensible
  {
    public PlayerExitGame() {}
    
    private int _fd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fd
    {
      get { return _fd; }
      set { _fd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerReLoadScene")]
  public partial class PlayerReLoadScene : global::ProtoBuf.IExtensible
  {
    public PlayerReLoadScene() {}
    
    private int _fd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fd
    {
      get { return _fd; }
      set { _fd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}