//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ServerProtocol.proto
namespace proto.serverproto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtocolNetResponse")]
  public partial class ProtocolNetResponse : global::ProtoBuf.IExtensible
  {
    public ProtocolNetResponse() {}
    
    private int _cmd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private proto.serverproto.ConnectToServerResponse _connectToServerResponse = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"connectToServerResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.serverproto.ConnectToServerResponse connectToServerResponse
    {
      get { return _connectToServerResponse; }
      set { _connectToServerResponse = value; }
    }
    private proto.serverproto.CreateRoomResponse _createRoomResponse = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"createRoomResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.serverproto.CreateRoomResponse createRoomResponse
    {
      get { return _createRoomResponse; }
      set { _createRoomResponse = value; }
    }
    private proto.serverproto.GetRoomListResponse _getRoomListResponse = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"getRoomListResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.serverproto.GetRoomListResponse getRoomListResponse
    {
      get { return _getRoomListResponse; }
      set { _getRoomListResponse = value; }
    }
    private proto.serverproto.JoinRoomResponse _joinRoomResponse = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"joinRoomResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.serverproto.JoinRoomResponse joinRoomResponse
    {
      get { return _joinRoomResponse; }
      set { _joinRoomResponse = value; }
    }
    private proto.serverproto.ExitRoomResponse _exitRoomResponse = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"exitRoomResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.serverproto.ExitRoomResponse exitRoomResponse
    {
      get { return _exitRoomResponse; }
      set { _exitRoomResponse = value; }
    }
    private proto.serverproto.RoomOwnerExitResponse _roomOwnerExitResponse = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"roomOwnerExitResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.serverproto.RoomOwnerExitResponse roomOwnerExitResponse
    {
      get { return _roomOwnerExitResponse; }
      set { _roomOwnerExitResponse = value; }
    }
    private proto.serverproto.RoomOwnerReadyStartGameResponse _roomOwnerReadyStartGameResponse = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"roomOwnerReadyStartGameResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.serverproto.RoomOwnerReadyStartGameResponse roomOwnerReadyStartGameResponse
    {
      get { return _roomOwnerReadyStartGameResponse; }
      set { _roomOwnerReadyStartGameResponse = value; }
    }
    private proto.serverproto.RoomOwnerStartGameResponse _roomOwnerStartGameResponse = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"roomOwnerStartGameResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.serverproto.RoomOwnerStartGameResponse roomOwnerStartGameResponse
    {
      get { return _roomOwnerStartGameResponse; }
      set { _roomOwnerStartGameResponse = value; }
    }
    private proto.serverproto.GameResultResponse _gameResultResponse = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"gameResultResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.serverproto.GameResultResponse gameResultResponse
    {
      get { return _gameResultResponse; }
      set { _gameResultResponse = value; }
    }
    private proto.serverproto.PlayerReloadSceneResponse _playerReloadSceneResponse = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"playerReloadSceneResponse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.serverproto.PlayerReloadSceneResponse playerReloadSceneResponse
    {
      get { return _playerReloadSceneResponse; }
      set { _playerReloadSceneResponse = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConnectToServerResponse")]
  public partial class ConnectToServerResponse : global::ProtoBuf.IExtensible
  {
    public ConnectToServerResponse() {}
    
    private int _fd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fd
    {
      get { return _fd; }
      set { _fd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRoomResponse")]
  public partial class CreateRoomResponse : global::ProtoBuf.IExtensible
  {
    public CreateRoomResponse() {}
    
    private bool _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SinglePlayerInfo")]
  public partial class SinglePlayerInfo : global::ProtoBuf.IExtensible
  {
    public SinglePlayerInfo() {}
    
    private string _userName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private int _fd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fd
    {
      get { return _fd; }
      set { _fd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SimpleRoomInfo")]
  public partial class SimpleRoomInfo : global::ProtoBuf.IExtensible
  {
    public SimpleRoomInfo() {}
    
    private string _roomOwner;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomOwner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomOwner
    {
      get { return _roomOwner; }
      set { _roomOwner = value; }
    }
    private int _currentManCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"currentManCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currentManCount
    {
      get { return _currentManCount; }
      set { _currentManCount = value; }
    }
    private int _maxManCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"maxManCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxManCount
    {
      get { return _maxManCount; }
      set { _maxManCount = value; }
    }
    private string _roomName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private int _roomOwnerFd;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"roomOwnerFd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomOwnerFd
    {
      get { return _roomOwnerFd; }
      set { _roomOwnerFd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetRoomListResponse")]
  public partial class GetRoomListResponse : global::ProtoBuf.IExtensible
  {
    public GetRoomListResponse() {}
    
    private bool _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _roomCount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomCount
    {
      get { return _roomCount; }
      set { _roomCount = value; }
    }
    private readonly global::System.Collections.Generic.List<proto.serverproto.SimpleRoomInfo> _roomInfo = new global::System.Collections.Generic.List<proto.serverproto.SimpleRoomInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.serverproto.SimpleRoomInfo> roomInfo
    {
      get { return _roomInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinRoomResponse")]
  public partial class JoinRoomResponse : global::ProtoBuf.IExtensible
  {
    public JoinRoomResponse() {}
    
    private bool _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _manCount = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"manCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int manCount
    {
      get { return _manCount; }
      set { _manCount = value; }
    }
    private readonly global::System.Collections.Generic.List<proto.serverproto.SinglePlayerInfo> _playerInfo = new global::System.Collections.Generic.List<proto.serverproto.SinglePlayerInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.serverproto.SinglePlayerInfo> playerInfo
    {
      get { return _playerInfo; }
    }
  
    private int _roomOwnerFd = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roomOwnerFd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomOwnerFd
    {
      get { return _roomOwnerFd; }
      set { _roomOwnerFd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExitRoomResponse")]
  public partial class ExitRoomResponse : global::ProtoBuf.IExtensible
  {
    public ExitRoomResponse() {}
    
    private bool _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _fd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fd
    {
      get { return _fd; }
      set { _fd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomOwnerExitResponse")]
  public partial class RoomOwnerExitResponse : global::ProtoBuf.IExtensible
  {
    public RoomOwnerExitResponse() {}
    
    private bool _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _fd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fd
    {
      get { return _fd; }
      set { _fd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomOwnerReadyStartGameResponse")]
  public partial class RoomOwnerReadyStartGameResponse : global::ProtoBuf.IExtensible
  {
    public RoomOwnerReadyStartGameResponse() {}
    
    private bool _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomOwnerStartGameResponse")]
  public partial class RoomOwnerStartGameResponse : global::ProtoBuf.IExtensible
  {
    public RoomOwnerStartGameResponse() {}
    
    private bool _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _seed;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"seed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seed
    {
      get { return _seed; }
      set { _seed = value; }
    }
    private float _maxSpeed = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"maxSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float maxSpeed
    {
      get { return _maxSpeed; }
      set { _maxSpeed = value; }
    }
    private float _speed = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private int _maxPower = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"maxPower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxPower
    {
      get { return _maxPower; }
      set { _maxPower = value; }
    }
    private int _power = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int power
    {
      get { return _power; }
      set { _power = value; }
    }
    private int _bubbleCount = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"bubbleCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bubbleCount
    {
      get { return _bubbleCount; }
      set { _bubbleCount = value; }
    }
    private int _maxBubbleCount = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"maxBubbleCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxBubbleCount
    {
      get { return _maxBubbleCount; }
      set { _maxBubbleCount = value; }
    }
    private float _boomTime = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"boomTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float boomTime
    {
      get { return _boomTime; }
      set { _boomTime = value; }
    }
    private float _maxDistance = default(float);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"maxDistance", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float maxDistance
    {
      get { return _maxDistance; }
      set { _maxDistance = value; }
    }
    private float _joystickPercent = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"joystickPercent", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float joystickPercent
    {
      get { return _joystickPercent; }
      set { _joystickPercent = value; }
    }
    private readonly global::System.Collections.Generic.List<proto.serverproto.PlayerGameInitInfo> _playerGameInitInfo = new global::System.Collections.Generic.List<proto.serverproto.PlayerGameInitInfo>();
    [global::ProtoBuf.ProtoMember(12, Name=@"playerGameInitInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.serverproto.PlayerGameInitInfo> playerGameInitInfo
    {
      get { return _playerGameInitInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerGameInitInfo")]
  public partial class PlayerGameInitInfo : global::ProtoBuf.IExtensible
  {
    public PlayerGameInitInfo() {}
    
    private int _fd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fd
    {
      get { return _fd; }
      set { _fd = value; }
    }
    private float _posX;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posX
    {
      get { return _posX; }
      set { _posX = value; }
    }
    private float _posY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posY
    {
      get { return _posY; }
      set { _posY = value; }
    }
    private string _posName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"posName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string posName
    {
      get { return _posName; }
      set { _posName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameResultResponse")]
  public partial class GameResultResponse : global::ProtoBuf.IExtensible
  {
    public GameResultResponse() {}
    
    private bool _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerReloadSceneResponse")]
  public partial class PlayerReloadSceneResponse : global::ProtoBuf.IExtensible
  {
    public PlayerReloadSceneResponse() {}
    
    private bool _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}